CREATE DATABASE IF NOT EXISTS EShop CHARACTER SET=utf8mb4;

CREATE USER IF NOT EXISTS 'eshop_user'@'localhost' IDENTIFIED BY 'F3h6R9sQ2f';

GRANT SELECT, INSERT, UPDATE, DELETE ON EShop.* TO 'ehop_user'@'localhost';